### ISSUE TITLE
Understanding this project.

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/S-array#1]
Hi @adamhaile  I may not have understood this project. As I understand it: 
```typescript
import SArray from 's-array';
import S, { DataSignal } from 's-js';

const list = SArray<number>([]);

const fn1 = () => {
  const listItems = list();
  //do some process with listItems
  console.log('fn1');
};
const fn2 = () => {
  const listItems = list();
  //do some process with listItems
  console.log('fn2');
};
const fn3 = () => {
  const listItems = list();
  //do some process with listItems
  console.log('fn3');
};

S(() => {
  S.freeze(() => {
    list.push(1);
    list.push(2);
    list.push(3);
  });
  fn1();
  fn2();
  fn3();
});

S.freeze(() => {
  console.log('---------------------');
  console.log('push item 4');
  list.push(4);
  console.log('push item 5');
  list.push(5);
  console.log('---------------------');
});

```
output is
```
fn1
fn2
fn3
---------------------
fn1
fn2
fn3
fn1
fn2
fn3
......
.......
---------------------
```

This is normal working. Binding s-array'ed  objects to UI working well. list.push inserts new dom node and list.splice removes.

But in a real project, arrays are difficult to manage. As in the previous example every `list.push(..)` method triggers all functions where `list()` is used. This can lead to unexpected results. Also can be performance problem in a large project.

**Comment by ismail-codar** [comment]
I say this as a brainstorming. 

First we want to create, update and delete actions to reflect user interface. 
Updating list items is no problem s-js makes it. 
We can convert all arrays to proxied arrays for detecting create and delete actions and reflecting this actions to dom.

**Comment by adamhaile** [comment]
Hi @ismail-codar --
If you want multiple pushes to only trigger downstream code once, you need to wrap them in a freeze:
```javascript
S.freeze(() => {
    list.push(4);
    list.push(5);
    console.log(list().length); // will still print 3, since state is immutable during a freeze
});
console.log(list().length); // now it will print 5
```
`SArray` provides both monitored mutation methods (like `push()`) *and* synchronous mutations, meaning mutations are deferred until the next tick.

**Comment by ismail-codar** [comment]
S.freeze works for this example. But my app a few complicated it must be something else I'am looking..

**Comment by ismail-codar** [comment]
I have updated above example not to rewrite on new comment. I am working on an experimental json editor. I guess problem is that ensure and consume in same place like: 
```js
S(() => {
  S.freeze(() => {
    list.push(1);
    list.push(2);
    list.push(3);
  });
  fn1(); 
  fn2();
  fn3();
});
```
Because I am using a map loop in jsx like the following. Surplus compiler puts all off to a S(...) section.``
`editor.codeList` type is SArray.
`styleIntentNewLine` method looks prev and next items from editor.codeList so uses `codeList()`
and codeItemClick provides `codeList.push`
```jsx
 {props.editor.codeList.map(item => (
          <span
            className={actions.styleIntentNewLine(props.editor, item)}
            ref={item.dom}
            onClick={actions.codeItemClick(props.editor, item)}
          >
            {actions.itemDisplay(
              item,
              props.editor.stateKeyToDisplay
            )}
          </span>
        ))}
```
![image](https://user-images.githubusercontent.com/282104/32536358-41237a22-c46f-11e7-9c66-4947803cd307.gif
)

**Comment by ismail-codar** [comment]
I do not know the mistake but currently I have implemented following method for using arrays to binding UI rather than this project. I'm working stress-free because codeList is now native array.

Usage:
```typescript
<code
        ref={codeListDom}
      >
        {sArrayMap(
          props.editor,
          'codeList',
          codeListDom,
          (item, index) => <span>render item</span>
        )}
</code>
```
```typescript
export const sArrayMap = (
  arrayContainer: any,
  arrayProperty: string,
  parentDom: HTMLElement,
  render: (item: any, idx?: number) => HTMLElement
) => {
  const disposers = [];
  let arrayLength = 0;
  let deletedIndex = -1;
  arrayContainer[arrayProperty] = new Proxy(arrayContainer[arrayProperty], {
    deleteProperty: function(target, property) {
      if (property == 'length') deletedIndex = -1;
      else parentDom.removeChild(parentDom.children.item(deletedIndex));
      disposers[deletedIndex]();
      disposers.splice(deletedIndex, 1);
      return true;
    },
    set: function(target, property, value) {
      if (property == 'length') {
        target[property] = value;
        arrayLength = value;
      } else {
        const index = Number(property);
        target[index] = value;
        if (index === arrayLength) {
          S.root(dispose => {
            disposers.push(dispose);
            parentDom.appendChild(render(value, index));
          });
        } else if (deletedIndex === -1) deletedIndex = index;
      }
      return true;
    }
  });
  return arrayContainer[arrayProperty].map(render);
};
```

**Comment by adamhaile** [comment]
That sounds like a neat app!

A lot going on here, and I'm not 100% sure I understand where you're having trouble, but a few notes:

- You wrote `onClick={actions.codeItemClick(props.editor, item)}`.  Does codeItemClick return a function, or should that be `onClick={() => actions.codeItemClick(props.editor, item)}`?

- `S.freeze()` is redundant inside a computation.  State is already frozen while we're updating computations.  `S.freeze()` is mainly used in action code, where we want all our changes (like an onClick handler performing multiple pushes to an SArray) to occur in the same instant.

- Yeah, your top example code is doing unchecked modifications to a signal it reads, which will cause an infinite mutation loop.  Computations that change data signals are essentially saying "given the current state of the world, the next state should be ...."   Your code says "however many items are in list(), add three."  So that will continue infinitely: 3 more, 6 more, 9 more, etc.  Usually, if you're modifying a signal you read, you have a condition you're checking first, and the modification will clear that condition (or at least clear it eventually).  So like:

```javascript
S(() => {
    if (isMissingRequiredElements(list())) {
        addRequiredElements(list);
    }
});
```
- In the JSX example you list, is your problem that the items in the array are being re-rendered with every addition?  Just making sure I've got the problem you're trying to solve.

**Comment by ismail-codar** [comment]
I actually produced my own solution. But I want to simulate the problem for the evolution of the surplus.

If there is my mistake we can develop documentation for me and other users. If there is something in the structure, it can be corrected.

Sharing all code can be difficult for you to understand my code. So I'll just do a simple application that simulates the problem over a period of time.

**Comment by ismail-codar** [comment]
I have uploaded a minimal example for simulating problem. If the line:27 commented on types.ts it works right. But currently multiple time writes console in this example.
*  `npm install` 
* `npm run start`
[array-problem.zip](https://github.com/adamhaile/S-array/files/1455356/array-problem.zip)

![problem](https://user-images.githubusercontent.com/282104/32573367-cd7ab99e-c4de-11e7-9b0c-1609ca53f18f.gif)

**Comment by ismail-codar** [comment]
Sorry I forgot to use `S.freeze` in this example, but it does not matter.

**Comment by adamhaile** [comment]
Hi Ismail --
Thanks for the example.  So what's going on is that styleIntentNewLine reads editor.codeList(), so when you push a new item onto editor.codeList(), all the styleIntentNewLine calculations need to re-run.  So you see increasing logs to the console.

Your solution doesn't hit the issue, because since you're using a plain array, it doesn't watch for changes to editor.codeList.

If styleIntentNewLine doesn't need to care about changes to editor.codeList(), then it can sample the value -- `S.sample(editor.codeList)` -- rather than dereference it -- `editor.codeList()`.  That's equivalent to what your solution is doing.  If styleIntentNewLine *does* need to care about changes to editor.codeList, then you indeed need to re-run those calculations when you add a new item.

There are techniques to reduce the complexity of calculations involving creating intermediate calculations that stash their values in S.value() cells, but I don't know enough about what styleIntentNewLine is doing to know whether that would work here or not.
-- Adam

**Comment by ismail-codar** [comment]
Thanks @adamhaile yes accessing data like `S.sample(editor.codeList)` works. Actually, I read it in the documentation. But I did not remember. This is the lesson to me. 

"A burnt child dreads the fire" or "example is better than precept".  We must make frequent mistakes section in documentation by examples.

This issue is an example to new users may fall into this line.
https://github.com/adamhaile/surplus/issues/19#issuecomment-340329766 is another one.

**Comment by griebd** [comment]
on this path, my mistake (https://github.com/adamhaile/surplus/issues/22) may be another case for this section... :wink:

**Comment by ismail-codar** [comment]
It is obsolete.
