### ISSUE TITLE
Splice inconsistent with native method + some suggestions

### ISSUE THREAD

**Issue by visj** [adamhaile/S-array#12]
The native splice method returns an array of the removed items (if any), whereas SArray currently just returns the array itself. As splice is probably not something you'd be using for chaining methods, is there any reason for not keeping it consistent with the native method? 

Had another suggestion also that it would be nice to add removeAt and moveItem, e.g. a handy shorthand for splice(index, 1) and one for moving items around in the array. 
I'm using this project for building webpages (I've borrowed your amazing content-algorithm from Surplus but instead of the compiler I created a small runtime inspired by ivi-html), and I've come across how many times I find myself using these two utility methods.

If it sounds good I can assemble a pull request. It would require changing some of the existing specs and would of course be a breaking change. I'm not sure what the policy is given that this project is still <1.0.  

Cheers on your work on this project! :+1:

**Comment by adamhaile** [comment]
Glad you're finding S interesting!

Good question.  So yeah, there's a reason `splice()` is this way.  Whether that's a good reason could be debated :). 

One of the important features of all the SArray methods is that they're synchronous, which is to say that the value of the signal doesn't change until the next tick.  For example, with `pop()`:

```js
const foo = SArray([ 0, 1, 2, 3 ]);

S.freeze(() => {
    foo.pop(); // returns 3
    foo.pop(); // returns 2
    foo(); // still returns [0, 1, 2, 3], as time hasn't advance so the signal hasn't changed
});

foo(); // now returns [ 0, 1 ]
```

(Being synchronous is a core design element of S.  It means that you don't need to worry about the order computations run in during an update, because they all see the same values.  When state advances in the next tick, they all then see the new values together.)

`pop()` is easy to achieve synchrony: I just keep a count of how many we've popped, so I know which one to return next.   When time advances, I use that count to chop that many off the end.  But splice is a lot harder.  Imagine calling `splice(1, 1) ... splice(0, 2)`.  The last call should return two values that weren't even next to each other at the start of the tick.  

Implementing this would effectively require keeping two copies of the array at all times: the current one and the next one.  The memory and perf costs of that didn't feel worth the benefit of mimicking the native `splice()`, so the current behavior was the compromise I came up with.

I've said a few times that SArray isn't my ideal model for collections in S, it was just convenient enough that I haven't come up with something better :).

**Comment by nordkost** [comment]
Ok, that makes sense, I understand why splice is implemented this way. 

One way to implement this would be something "Wagner-Fischer"-like with changesets. If we imagine you're example with a slight twist for complexity:
```javascript
const foo = SArray([ 0, 1, 2, 3 ]);
S.freeze(() => {
    foo.splice(1, 1); // changesets[1] = {action: "delete"};
    //Since [1] has been deleted, switch action to replace
    foo.splice(1, 0, 4); // changesets[1] = {action: "replace", value: 4};
    foo.splice(2, 2); //  changesets[2] = changesets[3] = {action: "delete"};
});
```

As this computation would be costly (returning the third splice value would require us to apply every other changeset before we can figure out what to return), you could add an optional boolean parameter which requests the native return value, and "opt out" of this in cases where this behavior is not required, which would lead to much lower default performance overhead.

It can be discussed how to implement the changeset data structure. An idea could be to implement it "lazily", pushing computations to a stack, only evaluating them if the return value is requested, in which case you would apply the changesets, compute the new array, return the value, and then cache this array. If no other mutations are performed afterwards, you can directly use this cached array when actually applying the changes to the actual underlying array backing SArray. If another changeset is pushed to the stack, you would apply this changeset to the cached array. This way, the user can decide whether or not the added memory overhead is worth it to obtain native compatibility.

A positive side-effect of a changeset structure would be that you could use it to optimize how `map()` reuses old computations for values that haven't changed. Instead of iterating over the arrays trying to find which values to reuse, you would quickly find them looking at the current changeset for this computational round. Another advantage of this would be that `map()` would reuse computations for primitive values, since it would see that an item has moved it's place, which would not be affected of whether or not it is prepended by equal values in the old array (right now, moving one of the ones in `[0,1,2,1]` can cause an incorrect computation to be reused, which I noticed when DOM elements have internal state not tracked by S, for instance the current value of an input element, and SArray reusing values "greedily" whenever an old item `===`-equals a new item).

The downside with this method is that you'd have to sacrifice the low performance overhead of the native mimicking of simpler methods such as `pop()` and `shift()` which is supported today. 

The pop/shift logic can however easily lead to bugs as the native mimicking has been implemented isolated to those methods. I think this example of how `pop()` works today is quite counter-intuitive.  
```javascript
var foo = SArray([0, 1, 2, 3]);
S.freeze(() => {
  foo.splice(2, 2);
  foo.pop(); // => 3
});
```

**Comment by visj** [comment]
Ok, that makes sense, I understand why splice is implemented this way.

One way to implement this would be something "Wagner-Fischer"-like with changesets. If we imagine you're example with a slight twist for complexity:
```javascript
const foo = SArray([ 0, 1, 2, 3 ]);
S.freeze(() => {
    foo.splice(1, 1); // changesets[1] = {action: "delete"};
    //Since [1] has been deleted, switch action to replace
    foo.splice(1, 0, 4); // changesets[1] = {action: "replace", value: 4};
    foo.splice(2, 2); //  changesets[2] = changesets[3] = {action: "delete"};
});
```
As this computation would be costly (returning the third splice value would require us to apply every other changeset before we can figure out what to return), you could add an optional boolean parameter which requests the native return value, and "opt out" of this in cases where this behavior is not required, which would lead to much lower default performance overhead.

It can be discussed how to implement the changeset data structure. An idea could be to implement it "lazily", pushing computations to a queue, only evaluating them if the return value is requested, in which case you would apply the computations, create the changesets, compute the new array, return the value, and then cache this array. If no other mutations are performed afterwards, you can directly use this cached array when actually applying the changes to the actual underlying array backing SArray. If another changeset is pushed to the queue, you would apply this changeset to the cached array. This way, the user can decide whether or not the added memory overhead is worth it to obtain native compatibility.

A positive side-effect of a changeset structure would be that you could use it to optimize how `map()` reuses old computations for values that haven't changed. Instead of iterating over the arrays trying to find which values to reuse, you would quickly find them looking at the current changeset for this computational round. Another advantage of this would be that `map()` would reuse computations for primitive values, since it would see that an item has moved it's place, which would not be affected of whether or not it is prepended by equal values in the old array (right now, moving one of the ones in [0,1,2,1] can cause an incorrect computation to be reused, which I noticed when DOM elements have internal state not tracked by S, for instance the current value of an input element, and SArray reusing values "greedily" whenever an old item `===`-equals a new item).

The downside with this method is that you'd have to sacrifice the low performance overhead of the native mimicking of simpler methods such as `pop()` and `shift()` which is supported today.

The pop/shift logic can however easily lead to bugs as the native mimicking has been implemented isolated to those methods. I think this example of how `pop()` works today is quite counter-intuitive.
```javascript
var foo = SArray([0, 1, 2, 3]);
S.freeze(() => {
  foo.splice(2, 2);
  foo.pop(); // => 3
});
```
I accidentally commented on another account, switched over to avoid confusion... :P

**Comment by nordkost** [comment]
???

Är du ute och programmeringsmissionerar, försöker du teknologifrälsa mig
din lurifax?? :P

**Comment by visj** [comment]
Here is an example of how I'm thinking you could implement this behavior:
```javascript
var foo = SArray([0,1,2,3]);
S.freeze(() => {
  foo.push(4);
  foo.pop();
});
```
Basically, what changesets would do is this:
```javascript
function _handlePush(newValue) {
  if (changesets.length < values.length) {
    // fast track, no modifications have been called involving the end of the array
    changesets[values.length] = {action: "insert", value: newValue};
  } else {
    changesets.push({action" insert", value: newValue});
  }
}

function _handlePop() {
  if (changesets.length < values.length) {
    // fast track, doesn't apply this time as we've already pushed.
    changesets[values.length - 1] = {action: "delete"}
  } else {
    changesets.pop();
  }
}
```
When actually calling SArray `update()` function, `changesets` is empty, e.g. we don't actually have to perform any changes to the underlying array. 

I might have slipped some errors into this code, it is meant more as pseudo-code to how this could be implemented to make it easier to understand :) I'm not sure how it would benchmark against just performing the actions themselves without changesets. If you think this is at all interesting I can see what I can assemble and put together some benchmarks.

**Comment by visj** [comment]
After experimenting with this idea I landed in your conclusion, that mimicking for instance splice would be very difficult. 

It would make more sense to for instance accept an optional callback when the mutation is actually run, if one really needs that. As SArray is more of a mutation queue than an array, I think that functionality would make more sense. An exception would be if one were to add S.array to the S-js core, then you could check for RunningNode === null internally, and when RunningNode is null, just apply the update, trigger `dirty(false)`, and then only apply updates in the `S.root(() => S.on(dirty....)` when dirty is true. Anyway, I'm closing this as it would be better as a suggestion to include a simple DataArrayNode class into S core rather than modifying this project.
