### ISSUE TITLE
.includes() returns computation instead of boolean

### ISSUE THREAD

**Issue by Qix-** [adamhaile/S-array#14]
Not really sure what's happening here, but `.includes()` returns a computation instead of a boolean. This caused kind of a headache for a short while trying to figure out why an if conditional was always evaluating to `true`.

```javascript
const a = Sarray([1, 2, 3, 4]);

if (a.includes(5)) {
    console.log('always hit!');
}
```

**Comment by Qix-** [comment]
Can you explain the design here?

```javascript
    it("behaves like Array.prototype.includes", function () {
        S.root(function () {
            var a = SArray([1, 3, 2]);
            expect(a.includes(3)()).toBe(true);
            expect(a.includes(4)()).toBe(false);
        });
    });
```

If you have to execute the return value of `.includes()` then by definition it's not the same behavior as `Array.prototype.includes` 😅

**Comment by adamhaile** [comment]
It's the same way `.map()` doesn't return an array but an array signal.  `.includes()` returns a boolean signal, because the value may change over time.  If you want the other behavior, you can do `a().includes(5)`.  In fact, the result of `a.includes(5)` is functionally equivalent to `() => a().includes(5)`.

**Comment by Qix-** [comment]
Will `a().includes(5)` be re-evaluated if e.g. `a.shift()` occurs, then?

If so, this can be closed :D

**Comment by Qix-** [comment]
Yes, yes it does. Idk why I couldn't have tested that myself.

Thanks Adam :)
